name: "CD (Entrega Continua): Main WorkFlow"

env:
  VERCEL_TOKEN: "algumvalor"
  VERCEL_ORG_ID: "outrovalor"
  VERCEL_PROJECT_ID: "sadasdas"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run installation
        run: npm install
      - name: Run Deploy
        run: npm run deploy:prod
