# This is a basic workflow to help you get started with Actions

name: "CI (Integração Continua): Primeira Action"

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, synchronize]

# Definindo o que queremos executar
jobs:
  linter: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run installation
        run: npm install

      - name: Run Linter
        run: npm run lint
